export const productsList = [
  {
    createdAt: "2024-12-10T09:20:32.843Z",
    name: "Oriental Rubber Chips",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Esse temporibus atque. Quis doloremque veniam natus voluptate excepturi culpa. Velit suscipit repellat. Ipsam praesentium eos velit illum voluptatum voluptates aut consectetur eveniet. Quisquam laborum nisi explicabo ipsam doloremque blanditiis accusamus.",
    stock: "5",
    price: "303.00",
    active: true,
    color: "salmon",
    id: "1",
  },
  {
    createdAt: "2024-12-09T22:17:58.824Z",
    name: "Handcrafted Concrete Chair",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Occaecati veniam nulla rerum sint dolore repudiandae maiores temporibus similique. Maiores omnis labore eaque similique. Consequuntur natus laborum neque impedit alias officiis sequi. Animi ratione eos sed distinctio illo.",
    stock: "6",
    price: "350.00",
    active: false,
    color: "orange",
    id: "2",
  },
  {
    createdAt: "2024-12-09T23:49:01.899Z",
    name: "Modern Rubber Shirt",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Accusamus necessitatibus occaecati quos quod provident cupiditate aut. Beatae unde quibusdam alias nobis quibusdam totam minima. Velit exercitationem possimus dolores nemo soluta totam consequuntur nihil. Nulla itaque recusandae. Accusamus magnam ut minima eum veniam quisquam non fugiat non.",
    stock: "2",
    price: "645.00",
    active: true,
    color: "teal",
    id: "3",
  },
  {
    createdAt: "2024-12-10T04:07:42.650Z",
    name: "Modern Steel Shirt",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Veritatis vitae eaque rem officiis esse esse aperiam. Rerum rerum explicabo quo commodi laborum eos autem tempore. Odio ea quibusdam. Pariatur provident quae non dolorem nisi dolore saepe nostrum.",
    stock: "9",
    price: "321.00",
    active: true,
    color: "fuchsia",
    id: "4",
  },
  {
    createdAt: "2024-12-10T07:13:55.874Z",
    name: "Ergonomic Granite Chips",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Fugiat itaque cupiditate at voluptatem ratione repellat voluptatibus quod excepturi. Omnis soluta excepturi. Maiores dignissimos nihil et nobis.",
    stock: "8",
    price: "623.00",
    active: true,
    color: "lavender",
    id: "5",
  },
  {
    createdAt: "2024-12-10T01:58:23.886Z",
    name: "Sleek Frozen Soap",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Eaque voluptatibus nihil non odio. Voluptatibus expedita saepe enim nostrum molestias quas numquam. Perspiciatis quae asperiores nobis consequuntur repudiandae quas deserunt voluptates.",
    stock: "8",
    price: "11.00",
    active: false,
    color: "violet",
    id: "6",
  },
  {
    createdAt: "2024-12-09T19:33:54.333Z",
    name: "Handcrafted Granite Chips",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Esse ducimus error incidunt commodi odit at eos. Corrupti perspiciatis doloremque voluptatibus similique tempora illum in. Eum veritatis ex dolores.",
    stock: "4",
    price: "938.00",
    active: true,
    color: "ivory",
    id: "7",
  },
  {
    createdAt: "2024-12-09T21:39:15.901Z",
    name: "Refined Plastic Chips",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Similique magni dicta exercitationem cupiditate velit sequi. Cumque magni earum cupiditate dolor nulla quibusdam. Harum enim voluptatibus minus id. Ea qui dignissimos magnam. Reprehenderit illum dolores.",
    stock: "6",
    price: "934.00",
    active: true,
    color: "mint green",
    id: "8",
  },
  {
    createdAt: "2024-12-10T09:29:33.735Z",
    name: "Refined Steel Gloves",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Fuga mollitia iure laborum dolorum. Voluptatem quidem dignissimos quasi atque culpa atque quas quis. Suscipit saepe excepturi animi voluptatum enim. Ipsum vitae tempore. Accusantium aut eum velit aut deleniti a maiores. Impedit possimus hic.",
    stock: "8",
    price: "194.00",
    active: false,
    color: "gold",
    id: "9",
  },
  {
    createdAt: "2024-12-09T15:28:57.045Z",
    name: "Electronic Metal Fish",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Perspiciatis eligendi quia magnam. Culpa quia modi provident quidem assumenda excepturi natus quibusdam. Corporis delectus quas quaerat iusto amet harum culpa. Nulla mollitia beatae aliquid autem quod. Autem culpa iste esse exercitationem voluptas. Accusantium doloribus debitis porro.",
    stock: "6",
    price: "791.00",
    active: false,
    color: "tan",
    id: "10",
  },
  {
    createdAt: "2024-12-09T21:05:30.977Z",
    name: "Recycled Wooden Salad",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Impedit soluta iure repellat fugit voluptatem earum. Nemo minima odio accusamus suscipit dolor odit iusto vitae. Optio accusamus similique fuga accusantium excepturi officia dolore iure magnam. Voluptatibus aperiam mollitia error ullam. Consequuntur necessitatibus corporis laudantium facere odio velit perspiciatis saepe.",
    stock: "3",
    price: "144.00",
    active: true,
    color: "orange",
    id: "11",
  },
  {
    createdAt: "2024-12-09T21:53:03.590Z",
    name: "Awesome Fresh Bacon",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Alias aspernatur temporibus consequuntur accusamus laboriosam. Ab eaque ad. Dolor ratione corrupti neque aliquam ad. Sint consectetur eos cupiditate enim eum magni laborum unde. Quam necessitatibus tenetur quia ab. Veniam cum esse voluptas a ea aut.",
    stock: "9",
    price: "417.00",
    active: false,
    color: "green",
    id: "12",
  },
  {
    createdAt: "2024-12-09T13:26:47.671Z",
    name: "Fantastic Granite Hat",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Beatae perspiciatis quasi voluptates quibusdam earum. Nam maiores dolor laudantium cupiditate non provident id nostrum. Expedita labore placeat tenetur neque perspiciatis. Sit dolorem facere. Occaecati unde veniam natus consequuntur sint. Inventore velit doloribus autem repudiandae voluptas.",
    stock: "1",
    price: "369.00",
    active: true,
    color: "orange",
    id: "13",
  },
  {
    createdAt: "2024-12-10T05:01:23.950Z",
    name: "Modern Fresh Chicken",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Aut esse rem necessitatibus suscipit delectus alias veniam eaque. Qui voluptatum odit veniam dolores inventore ab architecto repellat excepturi. Dolores commodi sapiente rerum ipsa totam laboriosam ea. Ratione numquam veritatis labore quae. Possimus qui reprehenderit vel vero.",
    stock: "6",
    price: "506.00",
    active: true,
    color: "lime",
    id: "14",
  },
  {
    createdAt: "2024-12-09T18:23:24.039Z",
    name: "Elegant Plastic Chicken",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Harum molestiae vitae deleniti totam eum aliquid. Culpa occaecati fugit mollitia error tempore facilis. Debitis aspernatur similique voluptates et. Libero similique minima exercitationem eveniet consequuntur. Optio facilis dolor vel porro quasi sapiente quaerat assumenda.",
    stock: "7",
    price: "58.00",
    active: true,
    color: "orange",
    id: "15",
  },
  {
    createdAt: "2024-12-09T15:06:40.239Z",
    name: "Handcrafted Fresh Hat",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Blanditiis doloribus est tempore assumenda. Amet tempora magnam sed nisi. Temporibus pariatur neque eligendi eveniet.",
    stock: "2",
    price: "321.00",
    active: false,
    color: "purple",
    id: "16",
  },
  {
    createdAt: "2024-12-09T18:07:38.391Z",
    name: "Unbranded Plastic Towels",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Harum possimus consectetur deleniti quis iste rerum dolorum magnam. Numquam culpa cupiditate laboriosam earum praesentium beatae quibusdam. Magni excepturi fuga nobis neque atque unde. Ducimus consectetur qui consequatur provident vitae. Natus dolorem at unde deserunt nostrum corrupti sapiente itaque quidem.",
    stock: "7",
    price: "562.00",
    active: true,
    color: "blue",
    id: "17",
  },
  {
    createdAt: "2024-12-10T04:59:18.798Z",
    name: "Ergonomic Wooden Table",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Rerum dignissimos iusto placeat iure maiores. Hic iusto tempora. Tenetur quia nisi exercitationem.",
    stock: "2",
    price: "272.00",
    active: false,
    color: "white",
    id: "18",
  },
  {
    createdAt: "2024-12-09T16:20:05.367Z",
    name: "Ergonomic Fresh Cheese",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Maxime nam eaque. Repellat fugit deleniti. Facilis incidunt explicabo. Soluta doloribus tempora doloremque harum commodi impedit amet. Blanditiis vero harum sequi qui rerum totam ut. Perferendis deleniti nesciunt quisquam quisquam.",
    stock: "4",
    price: "407.00",
    active: true,
    color: "ivory",
    id: "19",
  },
  {
    createdAt: "2024-12-10T04:23:26.733Z",
    name: "Bespoke Metal Table",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Officia minima quis. Ullam id voluptas ullam vitae dolor cum voluptatum nam. Omnis recusandae deleniti ad quasi nostrum aliquam.",
    stock: "5",
    price: "818.00",
    active: false,
    color: "grey",
    id: "20",
  },
  {
    createdAt: "2024-12-09T19:59:00.444Z",
    name: "Intelligent Bronze Chair",
    img: "https://loremflickr.com/640/480/food",
    description:
      "At perferendis inventore aut reiciendis. Dolore at vero dolor ab numquam eos earum id. Esse tenetur voluptatibus. Dolore voluptate quibusdam quasi esse ullam. Consectetur ea iste enim quod facilis. Enim beatae iste.",
    stock: "3",
    price: "496.00",
    active: false,
    color: "orange",
    id: "21",
  },
  {
    createdAt: "2024-12-10T01:17:48.279Z",
    name: "Small Soft Chips",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Porro dignissimos nostrum distinctio. Ea nostrum asperiores. Perspiciatis quos at id illum sequi.",
    stock: "3",
    price: "510.00",
    active: false,
    color: "turquoise",
    id: "22",
  },
  {
    createdAt: "2024-12-09T22:03:09.810Z",
    name: "Gorgeous Metal Pizza",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Quam libero omnis nesciunt. Odit soluta ipsa similique deserunt doloremque debitis provident. Tempore sequi doloribus id recusandae eius consequatur explicabo repellendus quidem. Consectetur tenetur vero.",
    stock: "2",
    price: "48.00",
    active: true,
    color: "green",
    id: "23",
  },
  {
    createdAt: "2024-12-10T11:14:59.587Z",
    name: "Refined Rubber Cheese",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Fugit blanditiis animi laudantium ipsum nemo atque quidem animi. Minus molestiae mollitia tempora labore consectetur voluptatem. Numquam iure laboriosam reiciendis animi deserunt rerum hic in explicabo. Nam porro voluptatum aut eos laboriosam explicabo laboriosam.",
    stock: "3",
    price: "54.00",
    active: true,
    color: "lime",
    id: "24",
  },
  {
    createdAt: "2024-12-10T11:39:42.796Z",
    name: "Rustic Wooden Gloves",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Nulla sunt error neque doloremque. Velit molestias natus recusandae. Occaecati odit autem. Placeat officia nostrum ab iste ducimus. Minima occaecati explicabo delectus repudiandae quae error laboriosam. Unde doloribus voluptatum iusto doloribus quam nisi laboriosam iste aperiam.",
    stock: "1",
    price: "798.00",
    active: false,
    color: "cyan",
    id: "25",
  },
  {
    createdAt: "2024-12-10T07:04:10.561Z",
    name: "Handcrafted Bronze Fish",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Minus sequi totam alias eaque quaerat et soluta dolor et. Expedita nisi occaecati maiores assumenda in quo odio explicabo repudiandae. Fugit tenetur quod.",
    stock: "4",
    price: "897.00",
    active: false,
    color: "violet",
    id: "26",
  },
  {
    createdAt: "2024-12-09T13:21:44.876Z",
    name: "Practical Granite Keyboard",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Culpa asperiores enim quis debitis iusto quaerat quasi. Consequuntur totam blanditiis odit nesciunt eum asperiores sunt nam facere. Voluptatibus excepturi nihil fuga quis et consequatur necessitatibus necessitatibus possimus. Saepe velit distinctio reprehenderit itaque odit explicabo. In recusandae dolore cupiditate fugiat. Soluta quas porro temporibus voluptatum quidem quo magnam id.",
    stock: "6",
    price: "804.00",
    active: false,
    color: "turquoise",
    id: "27",
  },
  {
    createdAt: "2024-12-10T04:30:04.639Z",
    name: "Handmade Concrete Ball",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Repudiandae sapiente culpa atque occaecati deserunt dolore veniam. Similique odio earum delectus et laboriosam doloribus voluptates. Quos cumque ea quia dicta nemo animi. Odit possimus amet sed veritatis. Illo molestiae esse harum enim corrupti suscipit corrupti amet.",
    stock: "5",
    price: "664.00",
    active: false,
    color: "gold",
    id: "28",
  },
  {
    createdAt: "2024-12-10T08:45:20.031Z",
    name: "Bespoke Concrete Pizza",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Omnis sit dolorum doloremque recusandae deserunt architecto expedita. Consectetur voluptate amet unde consequuntur suscipit. Numquam temporibus corporis error facilis aliquid. Odio nisi exercitationem ea explicabo. Provident consequatur exercitationem molestias repudiandae.",
    stock: "7",
    price: "401.00",
    active: true,
    color: "white",
    id: "29",
  },
  {
    createdAt: "2024-12-09T23:10:53.373Z",
    name: "Incredible Steel Chips",
    img: "https://loremflickr.com/640/480/food",
    description:
      "Minus vel cumque dolor inventore odit. Reprehenderit explicabo incidunt magni atque voluptatibus provident quod quisquam. Provident porro harum aliquid harum exercitationem. Voluptatum maxime facilis dolores molestias tempore molestiae suscipit.",
    stock: "6",
    price: "698.00",
    active: true,
    color: "red",
    id: "30",
  },
];
